mongo:
  build: ../mongodb
  ports:
    - "27017:27017"
  hostname:
    mongo
  volumes:
    - /var/lib/mongodb:/data/db
  privileged:
    true

spider:
  restart: always
  build: .
  links: 
    - mongo:mongo
  hostname:
    spider

