web:
  restart: always
  build: "./weather demo v.1.0"
  links:
    - mongo:mongo
    - cassnode1:cassandra
  ports:
    - "8081:8080"
  hostname:
    tomcat
  privileged:
    true

mongo:
  build: ./mongodb
  ports:
    - "27017:27017"
  hostname:
    mongo
  volumes:
    - /var/lib/mongodb:/data/db
  privileged:
    true

spider:
  restart: always
  build: "./proj. bigdata spider"
  links: 
    - mongo:mongo
  hostname:
    spider

cassnode1:
  build: ./cassandra
  links:
    - cassnode2
    - cassnode3
  hostname:
    cassnode1
  volumes:
    - /vdisk/data1:/var/lib/cassandra/data
  command: -name "DataGuard Cluster" -seeds "cassnode1,cassnode2,cassnode3"

cassnode2:
  build: ./cassandra
  links:
    - cassnode3
  hostname:
    cassnode2
  volumes:
    - /vdisk/data2:/var/lib/cassandra/data
  command: -name "DataGuard Cluster" -seeds "cassnode1,cassnode2,cassnode3"

cassnode3:
  build: ./cassandra
  hostname:
    cassnode3
  volumes:
    - /vdisk/data3:/var/lib/cassandra/data
  command: -name "DataGuard Cluster" -seeds "cassnode1,cassnode2,cassnode3"

